U7L4/U7L4/Models/ErrorViewModel.cs
namespace U7L4.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

U7L4/U7L4/Models/RedditSimpleResponse.cs
namespace U7L4.Models
{
    public class RedditSimpleResponse
    {
        public string kind { get; set; }
        public RedditSimpleResponse_Data data { get; set; }
    }

    public class RedditSimpleResponse_Data
    {
        public string after { get; set; }
        public RedditSimpleResponse_Data_Child[] children { get; set; }
    }

    public class RedditSimpleResponse_Data_Child
    {
        public string kind { get; set; }
        public RedditSimpleResponse_Data_Child_Data data { get; set; }
    }

    public class RedditSimpleResponse_Data_Child_Data
    {
        public string title { get; set; }
        public RedditSimpleResponse_Data_Child_Data_LinkFlairRichText[] link_flair_richtext { get; set; }
    }

    public class RedditSimpleResponse_Data_Child_Data_LinkFlairRichText
    {
        public string a { get; set; }
        public string e { get; set; }
        public string u { get; set; }
    }
}

U7L4/U7L4/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using U7L4.Models;

namespace U7L4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

U7L4/U7L4/Controllers/PaupersController.cs
using Microsoft.AspNetCore.Mvc;
using U7L4.Models;

namespace U7L4.Controllers
{
    public class PaupersController : Controller
    {
        private readonly ILogger<PaupersController> _logger;
        private readonly IHttpClientFactory _httpClientFactory;

        public PaupersController(ILogger<PaupersController> logger, IHttpClientFactory newHttpClientFactory)
        {
            _httpClientFactory = newHttpClientFactory;
            _logger = logger;
        }

        public IActionResult Index()
        {
            //1. First, create an HTTP Client via the Client Factory to enable the ability send and receive a response to the API:
            HttpClient httpClient = _httpClientFactory.CreateClient();

            //2. Second, find the URL to call the API, and set it as a constant for use later.
            const string redditApiUrl = "https://www.reddit.com/r/aww/.json";

            //3. See if you have to send the API anything. Nothing required in this case.

            //4. Create a Model that models the returned response from the API. 
            //See 'RedditSimpleResponse.cs'

            //5. Call the API using the GetFromJasonAsync method attached to the HTTP Client. 
            //Dont forget to add GetAwaiter() and GetResult()
            var apiResponse = httpClient.GetFromJsonAsync<RedditSimpleResponse>(redditApiUrl).GetAwaiter().GetResult();

            //6. Create a new instance of the API Response Model and store the API response you get into that instance.
            var redditPostsToDisplay = apiResponse;

            //Finally, pass the API Response Model instance to the view so we can see what what are working with!
            return View(redditPostsToDisplay);
        }
    }
}

U7L4/U7L4/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

U7L4/U7L4/Views/Paupers/Index.cshtml
@model U7L4.Models.RedditSimpleResponse

@{
    for (int i = 0; i < @Model.data.children.Count(); i++)
    {
        <div class="row">
            <p>@Model.data.children[i].data.title</p>
        @foreach (var currLink in @Model.data.children[i].data.link_flair_richtext)
        {
            <p style="padding-left: 75px">@Model.data.children[i].data.link_flair_richtext[i].a</p>
            <p style="padding-left: 75px">@Model.data.children[i].data.link_flair_richtext[i].e</p>
            <img  style="width: 300px; height: 150px; padding-left: 75px" src="@Model.data.children[i].data.link_flair_richtext[i].u"/>
        }
        </div>
    }
}

U7L4/U7L4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - U7L4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/U7L4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">U7L4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paupers" asp-action="Index">Pauper's Reddit Index</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - U7L4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>